// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvykowyC20uTbWRQBySXaEld_geWopSrk',
    appId: '1:150788122768:web:bb9b2614746870f3819015',
    messagingSenderId: '150788122768',
    projectId: 'bingung-di-bandung-db',
    authDomain: 'bingung-di-bandung-db.firebaseapp.com',
    storageBucket: 'bingung-di-bandung-db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBInaigb27QvDY2w-NaiSRHmIi2LZS6NM4',
    appId: '1:150788122768:android:221921825e913343819015',
    messagingSenderId: '150788122768',
    projectId: 'bingung-di-bandung-db',
    storageBucket: 'bingung-di-bandung-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCsdPAWHs1Wx6FeoWpCDGNve-5ekAGPLc',
    appId: '1:150788122768:ios:38345bf619b5e37f819015',
    messagingSenderId: '150788122768',
    projectId: 'bingung-di-bandung-db',
    storageBucket: 'bingung-di-bandung-db.appspot.com',
    iosBundleId: 'com.example.bingungDiBandung',
  );
}
